import { TRPCError } from "@trpc/server";
import { and, desc, eq, gte, inArray, lte } from "drizzle-orm";
import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { getDb } from "./db";
import { storagePut } from "./storage";
import { brandSettings, employeeStores, employees, formTemplateStores, formTemplates, inventoryDocumentLines, inventoryDocuments, inventorySnapshots, materialItemStores, materialItems, rolePermissions, storeAuditLogs, stores } from "../drizzle/schema";
import { 正規化貨品代號, 貨品代號正規表示式 } from "../shared/adminRules";
import { 判斷共用快照保存 } from "../shared/snapshotRules";

const SHARED_SNAPSHOT_KEY = "__shared_inventory__";
const snapshotSaveQueues = new Map<string, Promise<{ conflict: boolean; latestVersion: number }>>();
const itemInput = z.object({ 貨品代號: z.string().trim().transform(正規化貨品代號).refine(value => 貨品代號正規表示式.test(value), "貨品代號格式須為一個英文字母加六個數字"), 名稱: z.string().min(1), 單價: z.number().nonnegative(), 大值單位: z.string().min(1), 小值單位: z.string().min(1), 換算比例: z.number().int().positive() });
const documentInput = z.object({ 類型: z.enum(["purchase", "return", "scrap", "count"]), 日期: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), 備註: z.string().optional(), 明細: z.array(z.object({ 品項編號: z.number().int().positive(), 數量: z.number().positive(), 單位: z.string().min(1), 盤點數量: z.number().nonnegative().optional() })).min(1) });
const adminOnly = protectedProcedure.use(({ ctx, next }) => { if (ctx.user.role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "需要管理員權限" }); return next(); });
const requirePermission = (module: "purchase" | "return" | "scrap" | "count" | "inventory" | "report" | "admin", action: "create" | "update" | "delete") => protectedProcedure.use(async ({ ctx, next }) => { if (ctx.user.role === "admin") return next(); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "資料庫尚未連線" }); const rows = await db.select().from(rolePermissions).where(and(eq(rolePermissions.role, "staff"), eq(rolePermissions.module, module))).limit(1); const permission = rows[0]; const allowed = action === "create" ? permission?.canCreate : action === "update" ? permission?.canUpdate : permission?.canDelete; if (!allowed) throw new TRPCError({ code: "FORBIDDEN", message: "目前角色沒有此操作權限" }); return next(); });
const 寫入門市稽核 = async (db: any, ctx: any, store: any, 動作: string, before: unknown, after: unknown) => { await db.insert(storeAuditLogs).values({ operatorOpenId: String(ctx.user.openId), operatorName: String(ctx.user.name || ctx.user.openId), storeId: Number(store.id), storeCode: String(store.storeCode), storeName: String(store.name), action: 動作, beforeState: before ? JSON.stringify(before) : null, afterState: after ? JSON.stringify(after) : null }); };

export const appRouter = router({
  system: systemRouter,
  auth: router({ me: publicProcedure.query(opts => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }) }),
  brand: router({
    get: publicProcedure.query(async () => { const db = await getDb(); const row = (await db?.select().from(brandSettings).limit(1))?.[0]; return { 公司名稱: row?.companyName || "顏 水煎餃", Logo網址: row?.logoUrl || null }; }),
  }),
  employee: router({ login: publicProcedure.input(z.object({ 工號: z.string().min(1) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "資料庫尚未連線" }); const rows = await db.select().from(employees).where(and(eq(employees.employeeNo, input.工號), eq(employees.active, true))).limit(1); const employee = rows[0]; if (!employee) throw new TRPCError({ code: "UNAUTHORIZED", message: "員工工號不存在或已停用" }); const assigned = await db.select({ 編號: stores.id, 名稱: stores.name, 地址: stores.address }).from(employeeStores).innerJoin(stores, eq(employeeStores.storeId, stores.id)).where(and(eq(employeeStores.employeeId, employee.id), eq(stores.active, true))); const available = employee.role === "admin" ? await db.select({ 編號: stores.id, 名稱: stores.name, 地址: stores.address }).from(stores).where(eq(stores.active, true)) : assigned; return { 工號: employee.employeeNo, 姓名: employee.employeeNo === "F999001" && (!employee.name || employee.name === employee.employeeNo) ? "顏嘉輝" : employee.name, 角色: employee.role === "admin" ? "管理員" : "一般員工", 門市: available } as const; }), permissions: publicProcedure.input(z.object({ 工號: z.string().min(1) })).query(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "資料庫尚未連線" }); const employeeRows = await db.select({ role: employees.role }).from(employees).where(and(eq(employees.employeeNo, input.工號), eq(employees.active, true))).limit(1); const employee = employeeRows[0]; if (!employee) throw new TRPCError({ code: "UNAUTHORIZED", message: "員工工號不存在或已停用" }); return db.select().from(rolePermissions).where(eq(rolePermissions.role, employee.role)); }) }),
  inventory: router({
    loadSnapshot: publicProcedure.input(z.object({ 工號: z.string().min(1) })).query(async ({ input }) => { const db = await getDb(); if (!db) return null; const shared = await db.select({ payload: inventorySnapshots.payload }).from(inventorySnapshots).where(eq(inventorySnapshots.employeeNo, SHARED_SNAPSHOT_KEY)).limit(1); const rows = shared.length ? shared : await db.select({ payload: inventorySnapshots.payload }).from(inventorySnapshots).orderBy(desc(inventorySnapshots.snapshotVersion)).limit(1); if (!rows[0]) return null; try { return JSON.parse(rows[0].payload) as { 品項: unknown[]; 異動: unknown[]; 操作稽核?: unknown[]; 員工: unknown[]; 權限: unknown[] }; } catch { return null; } }),
    getSnapshotStatus: publicProcedure.input(z.object({ 工號: z.string().min(1) })).query(async () => { const db = await getDb(); if (!db) return { 版本: 0, 更新時間: null }; const shared = await db.select({ snapshotVersion: inventorySnapshots.snapshotVersion, payload: inventorySnapshots.payload, updatedAt: inventorySnapshots.updatedAt }).from(inventorySnapshots).where(eq(inventorySnapshots.employeeNo, SHARED_SNAPSHOT_KEY)).limit(1); const row = shared[0]; if (!row) return { 版本: 0, 更新時間: null }; let payloadVersion = 0; try { payloadVersion = Number((JSON.parse(row.payload) as { 版本?: number }).版本) || 0; } catch { /* 使用資料表版本 */ } return { 版本: Math.max(row.snapshotVersion ?? 0, payloadVersion), 更新時間: row.updatedAt?.toISOString() ?? null }; }),
    saveSnapshot: publicProcedure.input(z.object({ 工號: z.string().min(1), payload: z.object({ 品項: z.array(z.unknown()), 異動: z.array(z.unknown()), 操作稽核: z.array(z.unknown()).default([]), 員工: z.array(z.unknown()), 權限: z.array(z.unknown()), 版本: z.number().int().nonnegative().default(0) }) })).mutation(async ({ input }) => { const queueKey = SHARED_SNAPSHOT_KEY; const previous = snapshotSaveQueues.get(queueKey) ?? Promise.resolve({ conflict: false, latestVersion: 0 }); const current = previous.catch(() => ({ conflict: false, latestVersion: 0 })).then(async () => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "資料庫尚未連線" }); const existing = await db.select({ payload: inventorySnapshots.payload, snapshotVersion: inventorySnapshots.snapshotVersion }).from(inventorySnapshots).where(eq(inventorySnapshots.employeeNo, SHARED_SNAPSHOT_KEY)).limit(1); const existingPayload = existing[0]?.payload ? (() => { try { return JSON.parse(existing[0].payload) as { 版本?: number }; } catch { return {}; } })() : {}; const existingVersion = Math.max(existing[0]?.snapshotVersion ?? 0, existingPayload.版本 ?? 0); const versionResult = 判斷共用快照保存(existingVersion, input.payload.版本); if (versionResult.衝突) return { conflict: true, latestVersion: versionResult.最新版本 }; await db.insert(inventorySnapshots).values({ employeeNo: SHARED_SNAPSHOT_KEY, payload: JSON.stringify(input.payload), snapshotVersion: input.payload.版本 }).onDuplicateKeyUpdate({ set: { payload: JSON.stringify(input.payload), snapshotVersion: input.payload.版本 } }); return { conflict: false, latestVersion: versionResult.最新版本 }; }); snapshotSaveQueues.set(queueKey, current); try { const result = await current; return { success: true, conflict: Boolean(result?.conflict), latestVersion: result?.latestVersion ?? input.payload.版本 }; } finally { if (snapshotSaveQueues.get(queueKey) === current) snapshotSaveQueues.delete(queueKey); } }),
    listItems: publicProcedure.query(async () => (await getDb())?.select().from(materialItems).where(eq(materialItems.active, true)) ?? []),
    listFormTemplates: publicProcedure.query(async () => (await getDb())?.select().from(formTemplates).where(eq(formTemplates.active, true)) ?? []),
    listFormTemplatesForStore: publicProcedure.input(z.object({ 門市編號: z.number().int().positive() })).query(async ({ input }) => { const db = await getDb(); if (!db) return []; const templates = await db.select().from(formTemplates).where(eq(formTemplates.active, true)); const assignments = await db.select({ templateId: formTemplateStores.templateId }).from(formTemplateStores).where(and(eq(formTemplateStores.storeId, input.門市編號), eq(formTemplateStores.active, true))); const assignedIds = new Set(assignments.map(row => row.templateId)); const allAssigned = await db.select({ templateId: formTemplateStores.templateId }).from(formTemplateStores).where(eq(formTemplateStores.active, true)); const assignedTemplateIds = new Set(allAssigned.map(row => row.templateId)); return templates.filter(template => assignedIds.has(template.id) || !assignedTemplateIds.has(template.id)); }),
    createItem: adminOnly.input(itemInput).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "資料庫尚未連線" }); try { await db.insert(materialItems).values({ materialCode: input.貨品代號, name: input.名稱, unitPrice: input.單價.toFixed(2), largeUnit: input.大值單位, smallUnit: input.小值單位, conversionRatio: input.換算比例 }); } catch (error) { if (String(error).includes("Duplicate") || String(error).includes("duplicate")) throw new TRPCError({ code: "CONFLICT", message: "貨品代號或品項名稱已存在" }); throw error; } return { success: true }; }),
    updateItem: adminOnly.input(z.object({ 編號: z.number().int().positive(), data: itemInput })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); try { await db.update(materialItems).set({ materialCode: input.data.貨品代號, name: input.data.名稱, unitPrice: input.data.單價.toFixed(2), largeUnit: input.data.大值單位, smallUnit: input.data.小值單位, conversionRatio: input.data.換算比例 }).where(eq(materialItems.id, input.編號)); } catch (error) { if (String(error).includes("Duplicate") || String(error).includes("duplicate")) throw new TRPCError({ code: "CONFLICT", message: "貨品代號或品項名稱已存在" }); throw error; } return { success: true }; }),
    deleteItem: adminOnly.input(z.object({ 編號: z.number().int().positive() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.update(materialItems).set({ active: false }).where(eq(materialItems.id, input.編號)); return { success: true }; }),
    listDocuments: protectedProcedure.input(z.object({ 開始日期: z.string(), 結束日期: z.string(), 類型: z.enum(["purchase", "return", "scrap", "count"]).optional(), 門市編號: z.array(z.number().int().positive()).optional() })).query(async ({ ctx, input }) => { const db = await getDb(); if (!db) return []; const assignedRows = await db.select({ storeId: employeeStores.storeId }).from(employeeStores).where(eq(employeeStores.employeeId, ctx.user.id)); const allowedStoreIds = ctx.user.role === "admin" ? input.門市編號 : assignedRows.map(row => row.storeId); const filters = [gte(inventoryDocuments.documentDate, input.開始日期), lte(inventoryDocuments.documentDate, input.結束日期)]; if (input.類型) filters.push(eq(inventoryDocuments.type, input.類型)); if (allowedStoreIds?.length) filters.push(inArray(inventoryDocuments.storeId, allowedStoreIds)); else if (ctx.user.role !== "admin") filters.push(eq(inventoryDocuments.storeId, -1)); return db.select().from(inventoryDocuments).where(and(...filters)).orderBy(desc(inventoryDocuments.documentDate)); }),
    createDocument: protectedProcedure.input(documentInput.extend({ 門市編號: z.number().int().positive().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "資料庫尚未連線" }); if (ctx.user.role !== "admin") { const permissionRows = await db.select().from(rolePermissions).where(and(eq(rolePermissions.role, "staff"), eq(rolePermissions.module, input.類型))); const permission = permissionRows[0]; if (!permission?.canCreate) throw new TRPCError({ code: "FORBIDDEN", message: "目前角色沒有此新增權限" }); } let storeId = input.門市編號; const assignedRows = await db.select({ storeId: employeeStores.storeId }).from(employeeStores).where(eq(employeeStores.employeeId, ctx.user.id)); if (ctx.user.role !== "admin") { if (!storeId || !assignedRows.some(row => row.storeId === storeId)) throw new TRPCError({ code: "FORBIDDEN", message: "只能操作所屬門市資料" }); } if (input.類型 === "count") { const countFilters = [eq(inventoryDocuments.type, "count"), eq(inventoryDocuments.documentDate, input.日期)]; if (storeId) countFilters.push(eq(inventoryDocuments.storeId, storeId)); const exists = await db.select({ id: inventoryDocuments.id }).from(inventoryDocuments).where(and(...countFilters)).limit(1); if (exists.length) throw new TRPCError({ code: "CONFLICT", message: "該門市今日已完成盤點，每日只能提交一次" }); } const [created] = await db.insert(inventoryDocuments).values({ type: input.類型, documentDate: input.日期, employeeId: ctx.user.id, storeId, note: input.備註 }).$returningId(); for (const line of input.明細) await db.insert(inventoryDocumentLines).values({ documentId: created.id, itemId: line.品項編號, quantity: line.數量.toFixed(3), unit: line.單位, countedQuantity: line.盤點數量?.toFixed(3) }); return { id: created.id }; }),
  }),
  admin: router({
    getBrandSettings: adminOnly.query(async () => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "資料庫尚未連線" }); const row = (await db.select().from(brandSettings).limit(1))[0]; return { 編號: row?.id ?? null, 公司名稱: row?.companyName || "顏 水煎餃", Logo網址: row?.logoUrl || null, 更新人員: row?.updatedBy || null, 更新時間: row?.updatedAt?.toISOString() || null }; }),
    updateBrandSettings: adminOnly.input(z.object({ 公司名稱: z.string().trim().min(1).max(120), Logo資料: z.string().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "資料庫尚未連線" }); let logoKey: string | undefined; let logoUrl: string | undefined; if (input.Logo資料) { const match = input.Logo資料.match(new RegExp("^data:image\\/(png|jpeg|jpg|webp);base64,([A-Za-z0-9+\\/=]+)$")); if (!match) throw new TRPCError({ code: "BAD_REQUEST", message: "Logo 僅支援 PNG、JPG 或 WebP 圖片" }); const mime = match[1] === "image/jpg" ? "image/jpeg" : match[1]; const bytes = Buffer.from(match[2], "base64"); if (bytes.length > 2 * 1024 * 1024) throw new TRPCError({ code: "PAYLOAD_TOO_LARGE", message: "Logo 圖片不可超過 2 MB" }); const uploaded = await storagePut(`brand/logo.${mime.split("/")[1]}`, bytes, mime); logoKey = uploaded.key; logoUrl = uploaded.url; } const current = (await db.select().from(brandSettings).limit(1))[0]; const values = { companyName: input.公司名稱, ...(logoKey ? { logoKey, logoUrl } : {}), updatedBy: String(ctx.user.name || ctx.user.openId) }; if (current) await db.update(brandSettings).set(values).where(eq(brandSettings.id, current.id)); else await db.insert(brandSettings).values({ companyName: input.公司名稱, logoKey: logoKey ?? null, logoUrl: logoUrl ?? null, updatedBy: values.updatedBy }); const saved = (await db.select().from(brandSettings).limit(1))[0]; return { success: true, 公司名稱: saved?.companyName ?? input.公司名稱, Logo網址: saved?.logoUrl ?? null }; }),
    listEmployees: adminOnly.query(async () => (await getDb())?.select().from(employees).orderBy(desc(employees.createdAt)) ?? []),
    listAuditLogs: adminOnly.input(z.object({ 開始日期: z.string().optional(), 結束日期: z.string().optional(), 員工工號: z.string().optional(), 門市編號: z.number().int().positive().optional(), 動作: z.string().optional() }).optional()).query(async ({ input }) => { const db = await getDb(); if (!db) return []; const rows = await db.select({ employeeNo: inventorySnapshots.employeeNo, payload: inventorySnapshots.payload }).from(inventorySnapshots); const storeRows = await db.select().from(storeAuditLogs); const employeeRows = await db.select({ employeeNo: employees.employeeNo, name: employees.name }).from(employees); const names = new Map(employeeRows.map(row => [row.employeeNo, row.name])); const logs: Array<Record<string, unknown>> = []; for (const row of rows) { if (input?.員工工號 && row.employeeNo !== input.員工工號) continue; try { const payload = JSON.parse(row.payload) as { 操作稽核?: unknown[] }; for (const raw of payload.操作稽核 ?? []) { if (!raw || typeof raw !== "object") continue; const log = raw as Record<string, unknown>; const date = String(log.操作時間 ?? "").slice(0, 10); const storeId = Number(log.門市編號 ?? 0) || undefined; if (input?.開始日期 && date < input.開始日期) continue; if (input?.結束日期 && date > input.結束日期) continue; if (input?.門市編號 && storeId !== input.門市編號) continue; if (input?.動作 && String(log.動作 ?? "") !== input.動作) continue; logs.push({ ...log, 員工工號: row.employeeNo, 員工姓名: names.get(row.employeeNo) ?? row.employeeNo, 門市編號: storeId }); } } catch { /* 忽略損壞快照，保留其他稽核紀錄 */ } } for (const row of storeRows) { const date = new Date(row.createdAt).toISOString().slice(0, 10); if (input?.開始日期 && date < input.開始日期) continue; if (input?.結束日期 && date > input.結束日期) continue; if (input?.門市編號 && row.storeId !== input.門市編號) continue; if (input?.動作 && row.action !== input.動作) continue; logs.push({ 操作時間: row.createdAt.toISOString(), 員工工號: row.operatorOpenId, 員工姓名: row.operatorName, 門市編號: row.storeId, 門市名稱: `${row.storeCode}・${row.storeName}`, 動作: row.action, 內容: `門市${row.action}`, 異動前: row.beforeState ?? "—", 異動後: row.afterState ?? "—" }); } return logs.sort((a, b) => String(b.操作時間 ?? "").localeCompare(String(a.操作時間 ?? ""))); }),
    listInventoryTimeline: adminOnly.input(z.object({ 開始日期: z.string().optional(), 結束日期: z.string().optional(), 員工工號: z.string().optional(), 門市編號: z.number().int().positive().optional() }).optional()).query(async ({ input }) => { const db = await getDb(); if (!db) return []; const rows = await db.select({ payload: inventorySnapshots.payload }).from(inventorySnapshots).where(eq(inventorySnapshots.employeeNo, SHARED_SNAPSHOT_KEY)); const timeline: Array<Record<string, unknown>> = []; for (const row of rows) { try { const payload = JSON.parse(row.payload) as { 操作稽核?: unknown[] }; for (const raw of payload.操作稽核 ?? []) { if (!raw || typeof raw !== "object") continue; const log = raw as Record<string, unknown>; const operationTime = String(log.操作時間 ?? ""); const date = operationTime.slice(0, 10); const operator = String(log.操作人 ?? ""); const match = operator.match(/（([^）]+)）$/); const employeeNo = match?.[1] ?? operator; const employeeName = match ? operator.replace(/（[^）]+）$/, "") : operator; const storeId = Number(log.門市編號 ?? 0) || undefined; if (input?.開始日期 && date < input.開始日期) continue; if (input?.結束日期 && date > input.結束日期) continue; if (input?.員工工號 && employeeNo !== input.員工工號) continue; if (input?.門市編號 && storeId !== input.門市編號) continue; timeline.push({ 操作時間: operationTime, 員工工號: employeeNo, 員工姓名: employeeName, 門市編號: storeId, 門市名稱: log.門市名稱, 動作: log.動作, 內容: log.內容, 異動前: log.異動前, 異動後: log.異動後 }); } } catch { /* 略過損壞快照 */ } } return timeline.sort((a, b) => String(b.操作時間 ?? "").localeCompare(String(a.操作時間 ?? ""))); }),
    listItemStores: adminOnly.query(async () => (await getDb())?.select().from(materialItemStores) ?? []),
    setItemStores: adminOnly.input(z.object({ 品項編號: z.number().int().positive(), 門市編號: z.array(z.number().int().positive()) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.delete(materialItemStores).where(eq(materialItemStores.itemId, input.品項編號)); if (input.門市編號.length) await db.insert(materialItemStores).values(input.門市編號.map(storeId => ({ itemId: input.品項編號, storeId }))); return { success: true }; }),
    listStores: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); if (!db) return []; if (ctx.user.role === "admin") return db.select().from(stores).where(eq(stores.active, true)).orderBy(stores.storeCode); return db.select({ id: stores.id, storeCode: stores.storeCode, name: stores.name, address: stores.address, active: stores.active, createdAt: stores.createdAt, updatedAt: stores.updatedAt }).from(employeeStores).innerJoin(stores, eq(employeeStores.storeId, stores.id)).where(and(eq(employeeStores.employeeId, ctx.user.id), eq(stores.active, true))).orderBy(stores.storeCode); }),
    listAllStores: adminOnly.query(async () => { const db = await getDb(); if (!db) return []; return db.select().from(stores).orderBy(stores.active, desc(stores.storeCode)); }),
    listEmployeeStores: adminOnly.query(async () => { const db = await getDb(); if (!db) return []; return db.select({ 員工編號: employees.id, 工號: employees.employeeNo, 姓名: employees.name, 門市編號: stores.id, 門市代號: stores.storeCode, 門市: stores.name }).from(employeeStores).innerJoin(employees, eq(employeeStores.employeeId, employees.id)).innerJoin(stores, eq(employeeStores.storeId, stores.id)).orderBy(employees.employeeNo, stores.storeCode); }),
    createStore: adminOnly.input(z.object({ 門市代號: z.string().regex(/^\d{5}$/, "門市代號必須為固定五位數字"), 名稱: z.string().min(1), 地址: z.string().min(1) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const [created] = await db.insert(stores).values({ storeCode: input.門市代號, name: input.名稱, address: input.地址 }).$returningId(); await 寫入門市稽核(db, ctx, { id: created.id, storeCode: input.門市代號, name: input.名稱 }, "新增", null, { 門市代號: input.門市代號, 名稱: input.名稱, 地址: input.地址, 啟用: true }); return { success: true }; }),
    updateStore: adminOnly.input(z.object({ 編號: z.number().int().positive(), 門市代號: z.string().regex(/^\d{5}$/, "門市代號必須為固定五位數字"), 名稱: z.string().min(1), 地址: z.string().min(1), 啟用: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const beforeRows = await db.select().from(stores).where(eq(stores.id, input.編號)).limit(1); const before = beforeRows[0]; if (!before) throw new TRPCError({ code: "NOT_FOUND", message: "找不到門市" }); await db.update(stores).set({ storeCode: input.門市代號, name: input.名稱, address: input.地址, active: input.啟用 }).where(eq(stores.id, input.編號)); await 寫入門市稽核(db, ctx, before, input.啟用 === before.active ? "修改" : input.啟用 ? "啟用" : "停用", { 門市代號: before.storeCode, 名稱: before.name, 地址: before.address, 啟用: before.active }, { 門市代號: input.門市代號, 名稱: input.名稱, 地址: input.地址, 啟用: input.啟用 }); return { success: true }; }),
    deleteStore: adminOnly.input(z.object({ 編號: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const beforeRows = await db.select().from(stores).where(eq(stores.id, input.編號)).limit(1); const before = beforeRows[0]; if (!before) throw new TRPCError({ code: "NOT_FOUND", message: "找不到門市" }); await db.update(stores).set({ active: false }).where(eq(stores.id, input.編號)); await 寫入門市稽核(db, ctx, before, "停用", { 門市代號: before.storeCode, 名稱: before.name, 地址: before.address, 啟用: before.active }, { 門市代號: before.storeCode, 名稱: before.name, 地址: before.address, 啟用: false }); return { success: true }; }),
    setEmployeeStores: adminOnly.input(z.object({ 員工編號: z.number().int().positive(), 門市編號: z.array(z.number().int().positive()) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.delete(employeeStores).where(eq(employeeStores.employeeId, input.員工編號)); if (input.門市編號.length) await db.insert(employeeStores).values(input.門市編號.map(storeId => ({ employeeId: input.員工編號, storeId }))); return { success: true }; }),
    createEmployee: adminOnly.input(z.object({ 工號: z.string().min(1), 姓名: z.string().min(1), 角色: z.enum(["admin", "staff"]) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.insert(employees).values({ employeeNo: input.工號, name: input.姓名, role: input.角色 }); return { success: true }; }),
    updateEmployee: adminOnly.input(z.object({ 編號: z.number().int().positive(), 工號: z.string().min(1), 姓名: z.string().min(1), 角色: z.enum(["admin", "staff"]), 啟用: z.boolean() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.update(employees).set({ employeeNo: input.工號, name: input.姓名, role: input.角色, active: input.啟用 }).where(eq(employees.id, input.編號)); return { success: true }; }),
    disableEmployee: adminOnly.input(z.object({ 編號: z.number().int().positive() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.update(employees).set({ active: false }).where(eq(employees.id, input.編號)); return { success: true }; }),
    listPermissions: adminOnly.query(async () => (await getDb())?.select().from(rolePermissions) ?? []),
    listTemplates: adminOnly.query(async () => (await getDb())?.select().from(formTemplates).where(eq(formTemplates.active, true)) ?? []),
    listTemplateStores: adminOnly.query(async () => (await getDb())?.select().from(formTemplateStores) ?? []),
    setTemplateStores: adminOnly.input(z.object({ 表單編號: z.number().int().positive(), 門市編號: z.array(z.number().int().positive()) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.delete(formTemplateStores).where(eq(formTemplateStores.templateId, input.表單編號)); if (input.門市編號.length) await db.insert(formTemplateStores).values(input.門市編號.map(storeId => ({ templateId: input.表單編號, storeId }))); return { success: true }; }),
    createTemplate: adminOnly.input(z.object({ 類型: z.enum(["purchase", "return", "scrap", "count"]), 名稱: z.string().min(1), 品項編號: z.array(z.number().int().positive()).min(1), 預設單位: z.record(z.string(), z.string().min(1)).optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const itemIds = input.品項編號.map(id => ({ 品項編號: id, 預設單位: input.預設單位?.[String(id)] || "" })); await db.insert(formTemplates).values({ type: input.類型, name: input.名稱, itemIds: JSON.stringify(itemIds) }); return { success: true }; }),
    updateTemplate: adminOnly.input(z.object({ 編號: z.number().int().positive(), 名稱: z.string().min(1), 品項編號: z.array(z.number().int().positive()).min(1), 預設單位: z.record(z.string(), z.string().min(1)).optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); const itemIds = input.品項編號.map(id => ({ 品項編號: id, 預設單位: input.預設單位?.[String(id)] || "" })); await db.update(formTemplates).set({ name: input.名稱, itemIds: JSON.stringify(itemIds) }).where(eq(formTemplates.id, input.編號)); return { success: true }; }),
    deleteTemplate: adminOnly.input(z.object({ 編號: z.number().int().positive() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.update(formTemplates).set({ active: false }).where(eq(formTemplates.id, input.編號)); return { success: true }; }),
    updatePermission: adminOnly.input(z.object({ 角色: z.enum(["admin", "staff"]), 模組: z.enum(["purchase", "return", "scrap", "count", "inventory", "report", "admin"]), 新增: z.boolean(), 修改: z.boolean(), 刪除: z.boolean() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR" }); await db.insert(rolePermissions).values({ role: input.角色, module: input.模組, canCreate: input.新增, canUpdate: input.修改, canDelete: input.刪除 }).onDuplicateKeyUpdate({ set: { canCreate: input.新增, canUpdate: input.修改, canDelete: input.刪除 } }); return { success: true }; }),
  }),
});
export type AppRouter = typeof appRouter;
