name: Deploy Zip Content

on:
  push:
    branches:
      - main # 如果你的主要分支是 master，請改成 master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 程式碼
        uses: actions/checkout@v4

      - name: 解壓縮檔案
        run: |
          # 解壓你的煎餃庫存系統壓縮檔到 dist 暫存區
          unzip Pan-fried-dumplings-inventory.zip -d ./dist

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # 指定到解壓後的 client 資料夾
          branch: pages # 自動部署到 gh-pages 分支
